version: '3'

services:
  # PostgreSQL
  postgres:
    image: postgres:11.4
    hostname: postgres
    ports:
      - 5432:5432 # Bind host port 5432 to PostgreSQL port 5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
